const std = @import("std");

pub const agent_runtime = @import("agents/service.zig");
pub const agent_mailbox = @import("agents/mailbox.zig");
pub const agent_profile = @import("agents/profile.zig");
pub const agent_scope = @import("agents/scope.zig");
pub const agent_spec = @import("agents/spec.zig");
pub const agent_supervisor = @import("agents/supervisor.zig");
pub const auth = @import("auth/index.zig");
pub const auth_resolver = auth.resolver;
pub const auth_store = auth.store;
pub const auth_openai_codex = auth.openai_codex;
pub const config = @import("config/resolver.zig");
pub const config_file = @import("config/file.zig");
pub const workspace = @import("config/workspace.zig");
pub const context = @import("context/index.zig");
pub const docs_sync = @import("docs/sync.zig");
pub const evaluation = @import("evaluation/index.zig");
pub const executor = @import("executor/loop.zig");
pub const turn_payload = @import("executor/turn_payload.zig");
pub const memory = @import("memory/index.zig");
pub const workspace_runtime = tools.workspace_runtime;
pub const plugins = @import("plugins/index.zig");
pub const prompts = @import("prompts/index.zig");
pub const protocol_types = @import("../shared/protocol/types.zig");
pub const provider_runtime = @import("providers/openai_compatible.zig");
pub const provider_anthropic = @import("providers/anthropic.zig");
pub const provider_responses = @import("providers/responses.zig");
pub const provider_capability = @import("providers/capability.zig");
pub const provider_compat = @import("providers/compat.zig");
pub const provider_dispatch = @import("providers/dispatch.zig");
pub const provider_pricing = @import("providers/pricing.zig");
pub const provider_routes = @import("providers/routes.zig");
pub const scheduler = @import("scheduler/index.zig");
pub const session_store = @import("sessions/store.zig");
pub const session_summaries = @import("sessions/summaries.zig");
pub const session_history = @import("sessions/history.zig");
pub const tickets = @import("tickets/index.zig");
pub const tools = @import("tools/index.zig");
pub const tool_runtime = tools.runtime;

test "core namespace exposes executor and store" {
    std.testing.refAllDeclsRecursive(config_file);
    std.testing.refAllDeclsRecursive(workspace);
    std.testing.refAllDeclsRecursive(agent_profile);
    std.testing.refAllDeclsRecursive(agent_mailbox);
    std.testing.refAllDeclsRecursive(agent_scope);
    std.testing.refAllDeclsRecursive(agent_spec);
    std.testing.refAllDeclsRecursive(agent_supervisor);
    std.testing.refAllDeclsRecursive(tickets);
    std.testing.refAllDeclsRecursive(provider_routes);
    std.testing.refAllDeclsRecursive(evaluation);
    std.testing.refAllDeclsRecursive(memory);
    try std.testing.expect(@hasDecl(@This(), "executor"));
    try std.testing.expect(@hasDecl(@This(), "agent_profile"));
    try std.testing.expect(@hasDecl(@This(), "agent_scope"));
    try std.testing.expect(@hasDecl(@This(), "session_store"));
    try std.testing.expect(@hasDecl(@This(), "session_summaries"));
    try std.testing.expect(@hasDecl(@This(), "config"));
    try std.testing.expect(@hasDecl(@This(), "config_file"));
    try std.testing.expect(@hasDecl(@This(), "workspace"));
    try std.testing.expect(@hasDecl(@This(), "auth_store"));
    try std.testing.expect(@hasDecl(@This(), "auth_openai_codex"));
    try std.testing.expect(@hasDecl(@This(), "context"));
    try std.testing.expect(@hasDecl(@This(), "evaluation"));
    try std.testing.expect(@hasDecl(@This(), "memory"));
    try std.testing.expect(@hasDecl(@This(), "scheduler"));
    try std.testing.expect(@hasDecl(@This(), "tools"));
    try std.testing.expect(@hasDecl(@This(), "plugins"));
    try std.testing.expect(@hasDecl(@This(), "tickets"));
    try std.testing.expect(@hasDecl(@This(), "prompts"));
}
